logging.level.org.springframework:
  web: DEBUG
  transaction.interceptor: TRACE

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hw
    username: USERNAME
    password: PASSWORD
    driver-class-name: org.postgresql.Driver
